name: macOS Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

defaults:
  run:
    shell: bash

env:
  PROG:         cubiomes-viewer
  SOURCE_DIR:   ${{github.workspace}}

jobs:
  build:
    runs-on: macos-15
  workflow_dispatch:

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1
        with:
          version:      '5.15.2'
  workflow_dispatch:
          host:         'mac'
          target:       'desktop'
          arch:         'clang_64'
          archives:     'x86_64 qtbase qttools'
          cache:        true
          setup-python: false
  workflow_dispatch:

      - name: Build
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              qmake CONFIG+=release
              make -j$(sysctl -n hw.ncpu)

      - name: Deploy
        working-directory: ${{env.SOURCE_DIR}}
        run:  |
              macdeployqt ${{env.PROG}}.app -dmg
              mv ${{env.PROG}}.dmg ${{env.PROG}}-${{github.ref_name}}-macos.dmg

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Cubiomes Viewer ${{github.ref_name}}
          body: |
            Pre-built macOS binary for Minecraft 26.2.
          files: |
            ${{env.SOURCE_DIR}}/${{env.PROG}}-${{github.ref_name}}-macos.dmg
          draft: false
          prerelease: false
